#=================================================#
# Spring Boot configuration for the "dev" profile #
#=================================================#
spring:
  application:
    name: donus-code-challange
  profiles:
    active: dev
  # http://localhost:8090/h2-console -> database portal
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

api:
  version: v1/

server:
  port: 8090

logging:
  config: src/main/resources/logback-dev.xml